services:
  i2pd:
    image: purplei2p/i2pd:latest-release
    restart: unless-stopped
    # Option A: publish SAM for host access
    ports:
      - "7656:7656" # SAM
    volumes:
      - ./i2pd:/var/lib/i2pd
    command: >
      --sam.enabled=true
      --sam.address=0.0.0.0
      --sam.port=7656
      --httpproxy.enabled=false
      --socksproxy.enabled=false
      --loglevel=info
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "printf 'HELLO VERSION MIN=3.0 MAX=3.4\n' | nc -w 2 127.0.0.1 7656 | grep -q '^HELLO REPLY RESULT=OK'",
        ]
      interval: 10s
      timeout: 5s
      retries: 6

  rnsd:
    build: .
    # Or: image: yourname/reticulum:latest
    network_mode: host
    restart: unless-stopped
    environment:
      # Optional: map to your host user IDs; omit if you don't care
      PUID: 1000
      PGID: 1000
      # Choose where Reticulum stores config/keys
      DATA_DIR: /data
      # If you use I2P SAM:
      # I2P_SAM_ADDRESS: "127.0.0.1:7656"
    volumes:
      - ./reticulum:/data
    devices:
      []
      # Add ttyUSB devices here, eg. if you've connected an rnode module to your device
      # - /dev/serial/by-id/your-rnode-here:/dev/ttyUSB0
