services:
  i2pd:
    image: purplei2p/i2pd:latest-release
    restart: unless-stopped
    # Option A: publish SAM for host access
    ports:
      - "7656:7656" # SAM
    volumes:
      - ./i2pd:/var/lib/i2pd
    command: >
      --sam.enabled=true
      --sam.address=0.0.0.0
      --sam.port=7656
      --httpproxy.enabled=false
      --socksproxy.enabled=false
      --loglevel=info
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "printf 'HELLO VERSION MIN=3.0 MAX=3.4\n' | nc -w 2 127.0.0.1 7656 | grep -q '^HELLO REPLY RESULT=OK'",
        ]
      interval: 10s
      timeout: 5s
      retries: 6

  rnsd:
    build: .
    network_mode: host # recommended for AutoInterface/LAN discovery
    depends_on:
      i2pd:
        condition: service_healthy
    environment:
      I2P_SAM_ADDRESS: "127.0.0.1:7656" # reaches published host port
    volumes:
      - ./reticulum:/home/rns/.reticulum
    devices:
      []
      # If you add a LoRa device or something else, mount it
      # - /dev/serial/by-id/…:/dev/ttyUSB0
    restart: unless-stopped
